global:
  scrape_interval: 10s
rule_files:
  - "/etc/prometheus/rules/rule.yml"

scrape_configs:
  - job_name: 'num-notifications'
    static_configs:
      - targets: ['uservice_weather:8000', 'uservice_notifier:8000']