  kind: Cluster
  apiVersion: kind.x-k8s.io/v1alpha4
  nodes:
    - role: control-plane
      labels:
        custom-label: "control-plane"
      kubeadmConfigPatches:
        - |
          kind: InitConfiguration
          nodeRegistration:
            kubeletExtraArgs:
              node-labels: "ingress-ready=true"
      extraPortMappings:
        - containerPort: 80
          hostPort: 80
          protocol: TCP
        - containerPort: 443
          hostPort: 443
          protocol: TCP
        - containerPort: 30001
          hostPort: 30001
          protocol: TCP
    - role: worker
      labels:
        custom-label: "worker"

#   kind create cluster --config cluster.yaml
#   kubectl apply -f zookeeper.yaml,backend-networkpolicy.yaml,kafka.yaml,mongo-db.yaml,uservice-client.yaml,uservice-user.yaml,uservice-weather.yaml,uservice-notifier.yaml,proxy.yaml,prometheus.yaml,sla-manager.yaml
#   kubectl apply -f zookeeper.yaml,backend-networkpolicy.yaml
#   kubectl apply -f kafka.yaml,mongo-db.yaml,uservice-client.yaml,uservice-user.yaml,uservice-weather.yaml,uservice-notifier.yaml,proxy.yaml,prometheus.yaml,sla-manager.yaml
#   kubectl delete -f zookeeper.yaml,backend-networkpolicy.yaml,kafka.yaml,mongo-db.yaml,uservice-client.yaml,uservice-user.yaml,uservice-weather.yaml,uservice-notifier.yaml,proxy.yaml,prometheus.yaml,sla-manager.yaml
#   kind delete cluster