apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: uservice-client
  name: uservice-client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: uservice-client
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: uservice-client
    spec:
      containers:
        - env:    
            - name: BOT_TOKEN
              value: 6765515091:AAGSMzDzfw4f5zrrZ3FF8Lzboz5g2uUY9ZE 
            - name: REGISTER_USER
              value: http://proxy:80/uservice_client/register
            - name: REMOVE_USER
              value: http://proxy:80/uservice_client/remove
          image: docker.io/sebastianob/uservice_client
          name: uservice-client
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: uservice-client
  name: uservice-client
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: uservice-client
status:
  loadBalancer: {}
