apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: uservice-weather
  name: uservice-weather
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: uservice-weather
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: uservice-weather
    spec:
      containers:
        - env:
            - name: API_KEY
              value: 464c00ac0bbe3174a13b4ac72cdae20f
            - name: MONGO_DB
              value: mongodb://root:password@mongo-db:27017/weather_report_db?authSource=admin&authMechanism=SCRAM-SHA-256
            - name: UPDATE_INTERVAL
              value: "3"
          image: docker.io/sebastianob/uservice_weather
          name: uservice-weather
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: uservice-weather
  name: uservice-weather
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: uservice-weather
status:
  loadBalancer: {}
